trigger:
  batch: false
  branches:
    include:
    - master
    - topic/*
    #- users/*

pool: default

steps:
- bash: |
    echo "Build.SourceBranch=$BUILD_SOURCEBRANCH"
    echo "Build.SourceBranchName=$BUILD_SOURCEBRANCHNAME"
    echo "this is batch"
  displayName: 'Check build variables for the branch'
